version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  # FastAPI Backend - Simple Configuration
  backend:
    build: ./backend
    container_name: fastapi_backend
    environment:
      - DATABASE_URL=postgresql://user:secure_password_123@db:5432/appdb
    ports:
      - "8000:8000"
      - "3000:8000"  # Also expose on port 3000
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge