version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build: ./backend
    container_name: fastapi_backend
    environment:
      - DATABASE_URL=postgresql://user:secure_password_123@db:5432/appdb
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  # Next.js Frontend - Minimal version for low memory
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.minimal
    container_name: nextjs_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://DROPLET_IP_PLACEHOLDER:8000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    # Reduced memory limits for minimal build
    mem_limit: 128m
    memswap_limit: 256m

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
